config/routes.rb
Fblogin::Application.routes.draw do
    # Omniauth pure
    match "/signin" => "services#signin"
    match "/signout" => "services#signout"
  
    match '/auth/:service/callback' => 'services#create' 
    match '/auth/failure' => 'services#failure'
  
    resources :services, :only => [:index, :create, :destroy] do
      collection do
        get 'signin'
        get 'signout'
        get 'signup'
        post 'newaccount'
        get 'failure'
      end
    end
  
    # used for the demo application only
    resources :users, :only => [:index] do
      collection do
        get 'test'
      end
    end
     
  root :to => "users#index"

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :provider, :uid, :uname, :uemail
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :services
  
  attr_accessible :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  helper_method :user_signed_in?
  
  private  
      def current_user  
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]  
      end
      
      def user_signed_in?
        return 1 if current_user 
      end
        
      def authenticate_user!
        if !current_user
          flash[:error] = 'You need to sign in before accessing this page!'
          redirect_to signin_services_path
        end
      end    
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!, :except => [:create, :signin, :signup, :newaccount, :failure]
  
  protect_from_forgery :except => :create     # see https://github.com/intridea/omniauth/issues/203
  
  def create
    # get the service parameter from the Rails router
    params[:service] ? service_route = params[:service] : service_route = 'No service recognized (invalid callback)'
  
    # get the full hash from omniauth
    omniauth = request.env['omniauth.auth']
    
    # continue only if hash and parameter exist
    if omniauth and params[:service]
      # map the returned hashes to our variables first - the hashes differs for every service
      # create a new hash
      @authhash = Hash.new
      
      if service_route == 'facebook'
        omniauth['extra']['user_hash']['email'] ? @authhash[:email] =  omniauth['extra']['user_hash']['email'] : @authhash[:email] = ''
        omniauth['extra']['user_hash']['name'] ? @authhash[:name] =  omniauth['extra']['user_hash']['name'] : @authhash[:name] = ''
        omniauth['extra']['user_hash']['id'] ?  @authhash[:uid] =  omniauth['extra']['user_hash']['id'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] = omniauth['provider'] : @authhash[:provider] = ''
      elsif service_route == 'github'
        omniauth['user_info']['email'] ? @authhash[:email] =  omniauth['user_info']['email'] : @authhash[:email] = ''
        omniauth['user_info']['name'] ? @authhash[:name] =  omniauth['user_info']['name'] : @authhash[:name] = ''
        omniauth['extra']['user_hash']['id'] ? @authhash[:uid] =  omniauth['extra']['user_hash']['id'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] =  omniauth['provider'] : @authhash[:provider] = ''  
      elsif ['google', 'yahoo', 'twitter', 'myopenid', 'open_id'].index(service_route) != nil
        omniauth['user_info']['email'] ? @authhash[:email] =  omniauth['user_info']['email'] : @authhash[:email] = ''
        omniauth['user_info']['name'] ? @authhash[:name] =  omniauth['user_info']['name'] : @authhash[:name] = ''
        omniauth['uid'] ? @authhash[:uid] = omniauth['uid'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] = omniauth['provider'] : @authhash[:provider] = ''
      else        
        # debug to output the hash that has been returned when adding new services
        render :text => omniauth.to_yaml
        return
      end 
      
      if @authhash[:uid] != '' and @authhash[:provider] != ''    
        auth = Service.find_by_provider_and_uid(@authhash[:provider], @authhash[:uid])
        # if the user is currently signed in, he/she might want to add another account to signin
        if user_signed_in?
          if auth
            flash[:notice] = 'Your account at ' + @authhash[:provider].capitalize + ' is already connected with this site.'
            redirect_to services_path
          else
            current_user.services.create!(:provider => @authhash[:provider], :uid => @authhash[:uid], :uname => @authhash[:name], :uemail => @authhash[:email])
            flash[:notice] = 'Your ' + @authhash[:provider].capitalize + ' account has been added for signing in at this site.'
            redirect_to services_path
          end
        else
          if auth
            # signin existing user
            # in the session his user id and the service id used for signing in is stored
            session[:user_id] = auth.user.id
            session[:service_id] = auth.id
          
            flash[:notice] = 'Signed in successfully via ' + @authhash[:provider].capitalize + '.'
            redirect_to root_url
          else
            # this is a new user; show signup; @authhash is available to the view and stored in the sesssion for creation of a new user
            session[:authhash] = @authhash
            render signup_services_path
          end
        end
      else
        flash[:error] =  'Error while authenticating via ' + service_route + '/' + @authhash[:provider].capitalize + '. The service returned invalid data for the user id.'
        redirect_to signin_path
      end
    else
      flash[:error] = 'Error while authenticating via ' + service_route.capitalize + '. The service did not return valid data.'
      redirect_to signin_path
    end
  end

def newaccount
  if params[:commit] == "Cancel"
    session[:authhash] = nil
    session.delete :authhash
    redirect_to root_url
  else  # create account
    @newuser = User.new
    @newuser.name = session[:authhash][:name]
    @newuser.email = session[:authhash][:email]
    @newuser.services.build(:provider => session[:authhash][:provider], :uid => session[:authhash][:uid], :uname => session[:authhash][:name], :uemail => session[:authhash][:email])
    
    if @newuser.save!
      # signin existing user
      # in the session his user id and the service id used for signing in is stored
      session[:user_id] = @newuser.id
      session[:service_id] = @newuser.services.first.id
      
      flash[:notice] = 'Your account has been created and you have been signed in!'
      redirect_to root_url
    else
      flash[:error] = 'This is embarrassing! There was an error while creating your account from which we were not able to recover.'
      redirect_to root_url
    end  
  end
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @services = current_user.services.order('provider asc')
end

def destroy
  # remove an authentication service linked to the current user
  @service = current_user.services.find(params[:id])
  
  if session[:service_id] == @service.id
    flash[:error] = 'You are currently signed in with this account!'
  else
    @service.destroy
  end
  
  redirect_to services_path
end

def signout 
  if current_user
    session[:user_id] = nil
    session[:service_id] = nil
    session.delete :user_id
    session.delete :service_id
    flash[:notice] = 'You have been signed out!'
  end  
  redirect_to root_url
end

def failure
  flash[:error] = 'There was an error at the remote authentication service. You have not been signed in.'
  redirect_to root_url
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fblogin</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<section id="head">

    <section id="user">
        <% if user_signed_in? %>
            <nav id="nav_user">
                <ul>
                    <span><%= current_user.email %></span>
                    <li><%= link_to "Settings", services_path %>
                    <li><%= link_to "Sign out", signout_services_path %></li>
                </ul>
            </nav>
        <% else %>
            <nav id="nav_user">
                <ul>
                    <span>Sign in with:</span>
                    <li><%= link_to "Facebook", "/auth/facebook" %></li>
                    <li><%= link_to "Google", "/auth/google" %></li>
                    <li><%= link_to "Yahoo", "/auth/yahoo" %>
                    <li><%= link_to "MyOpenID", "/auth/myopenid" %>
                    <li><%= link_to "Other", signin_services_path %>
                </ul>
            </nav>
        <% end %>
    </section>

    <h1>Omniauth <sup>pure</sup></h1>
</section>

<section id="body">
    <section id="flash">
        <% flash.each do |key, value| %>
            <div class="flash <%= key %> round"><%= value %></div>
        <% end %>
    </section>

    <%= yield %>
</section>

</body>
</html>

app/views/services/_services_list.html.erb
<ul id="services_list">
    <li><%= link_to "/auth/facebook" do %><%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>Facebook<% end %></li>
    <li><%= link_to "/auth/google" do %><%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>Google<% end %></li>
    <li><%= link_to "/auth/yahoo" do %><%= image_tag "yahoo_64.png", :size => "64x64", :alt => "Yahoo" %>Yahoo<% end %></li>
    <li><%= link_to "/auth/twitter" do %><%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>Twitter<% end %></li>
    <li><%= link_to "/auth/github" do %><%= image_tag "github_64.png", :size => "64x64", :alt => "Github" %>Github<% end %></li>
    <li><%= link_to "/auth/aol" do %><%= image_tag "aol_64.png", :size => "64x64", :alt => "Aol" %>Aol<% end %></li>
    <li><%= link_to "/auth/myopenid" do %><%= image_tag "openid_64.png", :size => "64x64", :alt => "MyOpenID" %>MyOpenID<% end %></li>
    <li><%= link_to "/auth/open_id" do %><%= image_tag "openid_64.png", :size => "64x64", :alt => "OpenID" %>Other OpenID<% end %></li>
</ul>

app/views/services/index.html.erb
<section id="services_manage" class="services">

    <h1>Authentication Services - Settings</h1>

    <h2>You can use these accounts to sign in</h2>
    
    <% @services.each do |service| %>  
          <div class="service_in_use round">  
              <div class="service_img">
                    <% if ['aol', 'facebook', 'github', 'google', 'openid', 'twitter', 'yahoo'].index(service.provider) %>
                        <%= image_tag "#{service.provider}_64.png", :size => "64x64" %>
                    <% else %>
                        <%= image_tag "openid_64.png", :size => "64x64" %>
                    <% end %>
              </div>
            
              <div class="service_userdata">
                <% if service.uid.starts_with?('http') %>
                    <%= service.uid.scan(/http[s]*:\/\/.*?\//)[0] %>
                <% else %>
                    <%= service.provider.capitalize %>: <%= service.uid %>
                <% end %>
                <br />
                <%= service.uname if service.uname != '' %><br />
                <%= service.uemail if service.uemail != '' %><br />
                <% if session[:service_id] == service.id %>
                    <span>Signed in</span>
                <% else %>
                    <%= link_to "Remove this service", service, :confirm => 'Are you sure you want to remove this authentication?', :method => :delete, :class => "remove" %>
                <% end %>
              </div>
          </div>  
    <% end %>


    <div id="services_available">
        <h2>You can connect more accounts to sign in</h2>

        <%= render 'services_list'%>
    </div>  
</section>

app/views/services/signin.html.erb
<section id="services_signin" class="services">
    <h1>Sign in</h1>

    <p>
    You can sign up or sign in using one of your existing accounts at Facebook, Google, Yahoo, MyOpenID and other OpenID services. Please select the provider you want to use:
    </p>

    <div>
        <%= render "services_list" %>
    </div>
    
    <p class="clear">
    Don't have any of these accounts? Get your <%= link_to "MyOpenID", "http://www.myopenid.com/" %> or <%= link_to "GoogleID", "http://mail.google.com/mail/signup" %> now! If you want to learn more about OpenID or find more OpenID providers, you can get more information at <%= link_to "openid.net", "http://openid.net" %>.
    </p>
</section>

app/views/users/_services_list.html.erb
<ul id="services_list">
    <li><%= link_to "/auth/facebook" do %><%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>Facebook<% end %></li>
    <li><%= link_to "/auth/google" do %><%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>Google<% end %></li>
    <li><%= link_to "/auth/yahoo" do %><%= image_tag "yahoo_64.png", :size => "64x64", :alt => "Yahoo" %>Yahoo<% end %></li>
    <li><%= link_to "/auth/twitter" do %><%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>Twitter<% end %></li>
    <li><%= link_to "/auth/github" do %><%= image_tag "github_64.png", :size => "64x64", :alt => "Github" %>Github<% end %></li>
    <li><%= link_to "/auth/aol" do %><%= image_tag "aol_64.png", :size => "64x64", :alt => "Aol" %>Aol<% end %></li>
    <li><%= link_to "/auth/myopenid" do %><%= image_tag "openid_64.png", :size => "64x64", :alt => "MyOpenID" %>MyOpenID<% end %></li>
    <li><%= link_to "/auth/open_id" do %><%= image_tag "openid_64.png", :size => "64x64", :alt => "OpenID" %>Other OpenID<% end %></li>
</ul>

app/views/users/index.html.erb
<section id="services_manage" class="services">

    <h1>Authentication Services - Settings</h1>

    <h2>You can use these accounts to sign in</h2>
    
    <% @services.each do |service| %>  
          <div class="service_in_use round">  
              <div class="service_img">
                    <% if ['aol', 'facebook', 'github', 'google', 'openid', 'twitter', 'yahoo'].index(service.provider) %>
                        <%= image_tag "#{service.provider}_64.png", :size => "64x64" %>
                    <% else %>
                        <%= image_tag "openid_64.png", :size => "64x64" %>
                    <% end %>
              </div>
            
              <div class="service_userdata">
                <% if service.uid.starts_with?('http') %>
                    <%= service.uid.scan(/http[s]*:\/\/.*?\//)[0] %>
                <% else %>
                    <%= service.provider.capitalize %>: <%= service.uid %>
                <% end %>
                <br />
                <%= service.uname if service.uname != '' %><br />
                <%= service.uemail if service.uemail != '' %><br />
                <% if session[:service_id] == service.id %>
                    <span>Signed in</span>
                <% else %>
                    <%= link_to "Remove this service", service, :confirm => 'Are you sure you want to remove this authentication?', :method => :delete, :class => "remove" %>
                <% end %>
              </div>
          </div>  
    <% end %>


    <div id="services_available">
        <h2>You can connect more accounts to sign in</h2>

        <%= render 'services_list'%>
    </div>  
</section>

app/views/users/signin.html.erb
<section id="services_signin" class="services">
    <h1>Sign in</h1>

    <p>
    You can sign up or sign in using one of your existing accounts at Facebook, Google, Yahoo, MyOpenID and other OpenID services. Please select the provider you want to use:
    </p>

    <div>
        <%= render "services_list" %>
    </div>
    
    <p class="clear">
    Don't have any of these accounts? Get your <%= link_to "MyOpenID", "http://www.myopenid.com/" %> or <%= link_to "GoogleID", "http://mail.google.com/mail/signup" %> now! If you want to learn more about OpenID or find more OpenID providers, you can get more information at <%= link_to "openid.net", "http://openid.net" %>.
    </p>
</section>